### ISSUE TITLE
Configurar a estrutura do projeto 

### ISSUE THREAD

**Issue by LeoVPires** [JardiNaHora/backend#6]
Configurar a estrutura do projeto (pastas, módulos, dependências.

**Comment by pauloguilherme0** [comment]
A estrutura adotada para este projeto segue o padrão RESTful API.

A organização inicial das pastas, módulos e dependências do projeto veio do próprio SpringBoot, ao incializar um novo projeto.

**Comment by pauloguilherme0** [comment]
A estrutura adotada para este projeto segue o padrão RESTful API.

A organização inicial das pastas, módulos e dependências do projeto veio do próprio SpringBoot, ao incializar um novo projeto.
